# Generated by Django 4.2.4 on 2023-08-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlanCaseMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("test_plan_id", models.PositiveIntegerField()),
                ("testcase_id", models.PositiveIntegerField()),
                (
                    "testcase_status",
                    models.PositiveIntegerField(
                        choices=[(1, "待执行"), (2, "通过"), (3, "失败"), (4, "阻塞")],
                        default=1,
                        verbose_name="用例执行状态",
                    ),
                ),
                ("executor", models.PositiveIntegerField(verbose_name="执行人")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Testcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="用例标题")),
                ("desc", models.TextField(verbose_name="用例描述")),
                ("pre_step", models.TextField(verbose_name="前置条件")),
                ("step", models.TextField(verbose_name="用例步骤")),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[(1, "功能测试"), (2, "自动化测试")],
                        default=1,
                        verbose_name="Case类型",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="用例版本"),
                ),
                ("tree_node_id", models.PositiveIntegerField(verbose_name="所属节点ID")),
            ],
            options={
                "db_table": "testcase",
            },
        ),
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="测试计划名称")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestcaseSnapshot",
            fields=[
                (
                    "testcase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="testcase.testcase",
                    ),
                ),
                ("testcase_id", models.PositiveIntegerField(verbose_name="用例id")),
            ],
            options={
                "db_table": "testcase_snapshot",
            },
            bases=("testcase.testcase",),
        ),
    ]
