# Generated by Django 4.2.4 on 2023-08-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=256, verbose_name="项目名称")),
                ("desc", models.TextField(verbose_name="项目描述和内容")),
                ("is_del", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="RequirementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=256, verbose_name="需求名称")),
                ("desc", models.TextField(verbose_name="需求描述和内容")),
                ("create_user_id", models.PositiveIntegerField(verbose_name="创建人id")),
                ("update_user_id", models.PositiveIntegerField(verbose_name="修改人id")),
                ("project_id", models.PositiveIntegerField(db_index=True)),
                ("is_del", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "requirement",
            },
        ),
        migrations.CreateModel(
            name="TreeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=32)),
                ("project_id", models.PositiveIntegerField(null=True)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "tree_node",
            },
        ),
    ]
