# Generated by Django 4.2.4 on 2023-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treenode",
            name="project_id",
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="testcase_root_tree_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="测试用例树的父id"
            ),
        ),
    ]
