# Generated by Django 4.2.4 on 2023-08-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_treenode_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='create_user_id',
            field=models.PositiveIntegerField(default=0, verbose_name='创建人'),
        ),
    ]
