# Generated by Django 4.2.4 on 2023-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_requirementmodel_create_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmodel',
            name='create_user_id',
            field=models.PositiveIntegerField(default=1, verbose_name='创建人id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treenode',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
