# Generated by Django 4.2.4 on 2023-09-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_projectmodel_create_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'permissions': (('project_manager', 'manage project'), ('project_member', 'project team members'))},
        ),
    ]
