# Generated by Django 4.2.4 on 2023-09-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_projectmodel_options'),
        ('common', '0004_alter_requirementmodel_create_user_id_and_more'),
    ]

    operations = [
    ]
