# Generated by Django 4.2.4 on 2023-09-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_merge_20230905_1100'),
        ('common', '0005_remove_requirementmodel_project_id_and_more'),
    ]

    operations = [
    ]
