# Generated by Django 4.2.4 on 2023-11-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_merge_20230905_1100"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_del", models.BooleanField(default=False, verbose_name="是否删除")),
                ("name", models.CharField(max_length=32, verbose_name="目录名称")),
            ],
            options={
                "db_table": "common_directory",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_del", models.BooleanField(default=False, verbose_name="是否删除")),
                ("name", models.CharField(max_length=256, verbose_name="项目名称")),
                ("desc", models.TextField(verbose_name="项目描述和内容")),
            ],
            options={
                "db_table": "common_project",
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_del", models.BooleanField(default=False, verbose_name="是否删除")),
                ("name", models.CharField(max_length=256, verbose_name="需求名称")),
                ("desc", models.TextField(verbose_name="需求描述和内容")),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "db_table": "common_requirement",
            },
        ),
        migrations.DeleteModel(
            name="ProjectModel",
        ),
        migrations.DeleteModel(
            name="RequirementModel",
        ),
        migrations.DeleteModel(
            name="TreeNode",
        ),
        migrations.AddField(
            model_name="directory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directory",
                to="common.project",
                verbose_name="所属项目",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="directory",
            unique_together={("project", "name")},
        ),
    ]
